CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "status" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" bigint,
  "product_id" bigint,
  "quantity" int,
  "unit_price_snapshot" decimal
);

COMMENT ON COLUMN "carts"."user_id" IS 'Keycloak user id (uuid), referans - FK degil';
COMMENT ON COLUMN "carts"."status" IS 'ACTIVE, CHECKED_OUT, ABANDONED';
COMMENT ON COLUMN "cart_items"."product_id" IS 'Catalog Service referansi - FK degil';
COMMENT ON COLUMN "cart_items"."unit_price_snapshot" IS 'ekleme anindaki fiyat, degisirse eski fiyat kalsin diye';

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
