CREATE TABLE "inventory_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint,
  "sku" varchar,
  "quantity_available" int,
  "quantity_reserved" int DEFAULT 0,
  "warehouse_location" varchar,
  "updated_at" timestamp
);

CREATE TABLE "inventory_movements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_item_id" bigint,
  "movement_type" varchar,
  "quantity" int,
  "reference_order_id" bigint,
  "created_at" timestamp
);

COMMENT ON COLUMN "inventory_items"."product_id" IS 'Catalog referansi, unique olmali';
COMMENT ON COLUMN "inventory_movements"."movement_type" IS 'IN, OUT, RESERVED, RELEASED';
COMMENT ON COLUMN "inventory_movements"."reference_order_id" IS 'ilgiliyse Order referansi';

ALTER TABLE "inventory_movements" ADD FOREIGN KEY ("inventory_item_id") REFERENCES "inventory_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;
