CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "type" varchar,
  "subject" varchar,
  "body" text,
  "status" varchar,
  "sent_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "notification_templates" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_type" varchar,
  "subject_template" varchar,
  "body_template" text
);

COMMENT ON COLUMN "notifications"."type" IS 'EMAIL, SMS, PUSH';
COMMENT ON COLUMN "notifications"."status" IS 'PENDING, SENT, FAILED';
COMMENT ON COLUMN "notification_templates"."event_type" IS 'ORDER_CREATED, PAYMENT_SUCCESS, vb - Kafka event tipiyle eslesir';
