CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "status" varchar,
  "total_amount" decimal,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "product_id" bigint,
  "quantity" int,
  "unit_price" decimal
);

CREATE TABLE "order_status_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "status" varchar,
  "changed_at" timestamp,
  "note" varchar
);

COMMENT ON COLUMN "orders"."user_id" IS 'Keycloak user id';
COMMENT ON COLUMN "orders"."status" IS 'PENDING, CONFIRMED, PAID, SHIPPED, DELIVERED, CANCELLED';
COMMENT ON COLUMN "order_items"."product_id" IS 'Catalog referansi';

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "order_status_history" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;
