CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "amount" decimal,
  "status" varchar,
  "payment_method" varchar,
  "transaction_id" varchar,
  "created_at" timestamp
);

CREATE TABLE "payment_transactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "payment_id" bigint,
  "type" varchar,
  "amount" decimal,
  "status" varchar,
  "created_at" timestamp
);

COMMENT ON COLUMN "payments"."order_id" IS 'Order Service referansi';
COMMENT ON COLUMN "payments"."status" IS 'PENDING, SUCCESS, FAILED, REFUNDED';
COMMENT ON COLUMN "payments"."payment_method" IS 'CREDIT_CARD, PAYPAL, vb';
COMMENT ON COLUMN "payments"."transaction_id" IS 'odeme saglayicisindan gelen referans';
COMMENT ON COLUMN "payment_transactions"."type" IS 'CHARGE, REFUND, RETRY';

ALTER TABLE "payment_transactions" ADD FOREIGN KEY ("payment_id") REFERENCES "payments" ("id") DEFERRABLE INITIALLY IMMEDIATE;
