CREATE TABLE "recommendations" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "product_id" bigint,
  "score" decimal,
  "reason" varchar,
  "generated_at" timestamp
);

CREATE TABLE "user_interactions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "product_id" bigint,
  "interaction_type" varchar,
  "created_at" timestamp
);

COMMENT ON COLUMN "recommendations"."product_id" IS 'Catalog referansi';
COMMENT ON COLUMN "recommendations"."score" IS 'oneri skoru, siralama icin';
COMMENT ON COLUMN "recommendations"."reason" IS 'RULE_BASED, ML_MODEL - ileride ML entegrasyonu icin';
COMMENT ON COLUMN "user_interactions"."interaction_type" IS 'VIEW, ADD_TO_CART, PURCHASE';
