CREATE TABLE "reviews" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "product_id" bigint,
  "rating" int,
  "comment" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "review_votes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "review_id" bigint,
  "user_id" bigint,
  "is_helpful" boolean
);

COMMENT ON COLUMN "reviews"."product_id" IS 'Catalog referansi';
COMMENT ON COLUMN "reviews"."rating" IS '1-5 arasi';

ALTER TABLE "review_votes" ADD FOREIGN KEY ("review_id") REFERENCES "reviews" ("id") DEFERRABLE INITIALLY IMMEDIATE;
