CREATE TABLE "shipments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "status" varchar,
  "carrier" varchar,
  "tracking_number" varchar,
  "shipped_at" timestamp,
  "delivered_at" timestamp,
  "created_at" timestamp
);

CREATE TABLE "shipping_addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "shipment_id" bigint,
  "address_line1" varchar,
  "address_line2" varchar,
  "city" varchar,
  "postal_code" varchar,
  "country" varchar
);

COMMENT ON COLUMN "shipments"."order_id" IS 'Order referansi';
COMMENT ON COLUMN "shipments"."status" IS 'PREPARING, SHIPPED, IN_TRANSIT, DELIVERED';

ALTER TABLE "shipping_addresses" ADD FOREIGN KEY ("shipment_id") REFERENCES "shipments" ("id") DEFERRABLE INITIALLY IMMEDIATE;
