CREATE TABLE user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
  user_id VARCHAR(36) NOT NULL UNIQUE,
  phone_number VARCHAR,
  date_of_birth DATE,
  default_address_line VARCHAR,
  default_city VARCHAR,
  default_postal_code VARCHAR,
  default_country VARCHAR,
  preferences TEXT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);
