server:
  port: 8081

spring:
  application:
    name: core-service

  datasource:
    catalog:
      url: jdbc:postgresql://localhost:5432/catalog_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    cart:
      url: jdbc:postgresql://localhost:5432/cart_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    order:
      url: jdbc:postgresql://localhost:5432/order_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    payment:
      url: jdbc:postgresql://localhost:5432/payment_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
    inventory:
      url: jdbc:postgresql://localhost:5432/inventory_db
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: core-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

keycloak:
  admin:
    base-url: http://localhost:8080
    realm: ecommerce-realm
    token-uri: http://localhost:8080/realms/ecommerce-realm/protocol/openid-connect/token
    client-id: core-service-admin-client
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
